import "server-only";

import { resolveEngine } from "@/lib/scout/reports/pdf";

function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Roboto, Arial, sans-serif;
      color: #1e293b;
      line-height: 1.6;
      padding: 40px 48px;
    }
    h1.doc-title {
      font-size: 22px;
      font-weight: 700;
      color: #0f172a;
      margin-bottom: 24px;
      padding-bottom: 12px;
      border-bottom: 2px solid #e2e8f0;
    }
    .doc-body h1 { font-size: 20px; font-weight: 700; margin: 20px 0 10px; }
    .doc-body h2 { font-size: 17px; font-weight: 600; margin: 16px 0 8px; }
    .doc-body h3 { font-size: 14px; font-weight: 600; margin: 12px 0 6px; }
    .doc-body p { margin: 6px 0; font-size: 13px; }
    .doc-body ul { list-style-type: disc; padding-left: 24px; margin: 8px 0; }
    .doc-body ol { list-style-type: decimal; padding-left: 24px; margin: 8px 0; }
    .doc-body li { margin: 4px 0; font-size: 13px; }
    .doc-body li p { margin: 0; }
    .doc-body blockquote {
      border-left: 3px solid #cbd5e1;
      padding-left: 12px;
      color: #64748b;
      margin: 10px 0;
    }
    .doc-body table {
      border-collapse: collapse;
      width: 100%;
      margin: 12px 0;
    }
    .doc-body th, .doc-body td {
      border: 1px solid #94a3b8;
      padding: 6px 10px;
      text-align: left;
      font-size: 12px;
    }
    .doc-body th { background: #f1f5f9; font-weight: 600; }
    .doc-body hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
    .doc-body img { max-width: 100%; height: auto; border-radius: 6px; }
    .doc-body strong { font-weight: 600; }
    .doc-body em { font-style: italic; }
    .doc-body u { text-decoration: underline; }
    .doc-body s { text-decoration: line-through; }
    .footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #94a3b8;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1 class="doc-title">${escapeHtml(title)}</h1>
  <div class="doc-body">${body}</div>
  <div class="footer">Generated by Fitoverse CRM</div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function renderInsightPdf(
  title: string,
  body: string,
): Promise<Buffer> {
  const html = wrapHtml(title, body);
  const engine = await resolveEngine();
  const puppeteer = (await import("puppeteer-core")).default;
  const browser = await puppeteer.launch({
    executablePath: engine.executablePath,
    args: [
      ...engine.args,
      "--no-sandbox",
      "--disable-dev-shm-usage",
      "--font-render-hinting=none",
    ],
    headless: engine.headless,
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load", timeout: 30_000 });
    await page
      .evaluate(() => document.fonts.ready.then(() => undefined))
      .catch(() => undefined);
    await page.emulateMediaType("print");

    const bytes = Buffer.from(
      await page.pdf({
        format: "A4",
        printBackground: true,
        displayHeaderFooter: false,
        margin: { top: "15mm", bottom: "15mm", left: "12mm", right: "12mm" },
        timeout: 30_000,
      }),
    );
    return bytes;
  } finally {
    await browser.close().catch(() => undefined);
  }
}
