import type { GuideEntry, SectionRecording } from "../types";

export const WHATSAPP_ENTRIES: GuideEntry[] = [
  // ── Inbox ──────────────────────────────────────────────
  {
    slug: "inbox-basics",
    title: "How to use the Inbox",
    summary: "Read and reply to WhatsApp conversations, send media, and assign chats to team members.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["inbox", "chat", "conversation", "reply", "message", "assign"],
    steps: [
      { text: "Click **Inbox** in the sidebar", target: "wa-sidebar-inbox" },
      { text: "Select a conversation from the left panel to open it" },
      { text: "Type your reply in the message box at the bottom and hit **Send**" },
      { text: "Use the **attachment icon** to send images, videos, or documents" },
      { text: "Click the **contact name** at the top to view their profile or assign the chat" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-inbox-basics.png",
      alt: "Inbox page showing conversation list and message composer",
    },
  },
  {
    slug: "quick-replies",
    title: "How to use quick replies",
    summary: "Save and reuse message snippets in the Inbox to reply faster.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["quick reply", "snippet", "canned", "template", "inbox"],
    steps: [
      { text: "Open a conversation in the **Inbox**", target: "wa-sidebar-inbox" },
      { text: "Click the **/ (slash)** icon in the message composer" },
      { text: "Pick a saved reply from the list, or type to search" },
      { text: "Edit the message if needed, then hit **Send**" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-quick-replies.png",
      alt: "Inbox conversation with quick reply menu open",
    },
  },

  // ── Contacts ───────────────────────────────────────────
  {
    slug: "manage-contacts",
    title: "How to add and manage contacts",
    summary: "Add new WhatsApp contacts, edit details, apply tags, and export your contact list.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["contact", "add", "create", "edit", "export", "manage"],
    steps: [
      { text: "Click **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click **+ Add Contact** at the top-right to create a new contact" },
      { text: "Fill in the name, phone number, and optional tags" },
      { text: "Click a contact row to view/edit their details, conversation history, and tags" },
      { text: "Use the **Export** button to download your contact list as a CSV" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-manage-contacts.png",
      alt: "Contacts page with add button and contact list",
    },
  },
  {
    slug: "filter-contacts-tag",
    title: "How to filter contacts by tag",
    summary: "Use tags to segment your WhatsApp contacts list for targeted broadcasts.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["contacts", "filter", "tag", "segment"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click the **Tags** filter dropdown above the table" },
      { text: "Select one or more tags — the list updates instantly" },
      { text: "Use the filtered list to start a broadcast or export contacts" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-filter-contacts.png",
      alt: "Contacts page with tag filter applied",
    },
  },
  {
    slug: "tags",
    title: "How to manage tags",
    summary: "Create, edit, and color-code tags to organize your contacts into meaningful groups.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["tags", "label", "color", "organize", "group", "category"],
    steps: [
      { text: "Open **Tags** from the All Tools menu in the sidebar" },
      { text: "Click **+ New Tag** to create a new tag" },
      { text: "Enter a tag name and pick a color" },
      { text: "Click **Save** — the tag is now available when tagging contacts" },
      { text: "Click the **edit icon** on any tag to rename or change its color" },
    ],
    screenshot: {
      path: "/tags",
      file: "wa-tags.png",
      alt: "Tags management page with color-coded tags",
    },
  },

  // ── Broadcasts ─────────────────────────────────────────
  {
    slug: "send-broadcast",
    title: "How to send a broadcast",
    summary: "Create and send a WhatsApp broadcast to a filtered set of contacts using a pre-approved template.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["broadcast", "send", "template", "bulk", "message"],
    steps: [
      { text: "Click **Broadcasts** in the sidebar", target: "wa-sidebar-broadcasts" },
      { text: "Click the **New Broadcast** button at the top-right", target: "wa-broadcast-create" },
      { text: "Select a **template** from the dropdown — only approved templates appear" },
      { text: "Use the **filters** to pick which contacts receive the broadcast (tags, date, etc.)" },
      { text: "Review the preview on the right, then click **Send Broadcast**" },
    ],
    screenshot: {
      path: "/broadcasts",
      file: "wa-send-broadcast.png",
      alt: "Broadcasts page with the New Broadcast button highlighted",
    },
  },
  {
    slug: "broadcast-analytics",
    title: "How to view broadcast analytics",
    summary: "Track delivery rates, read rates, and trends for all your broadcasts.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["analytics", "broadcast", "delivery", "read", "performance", "stats"],
    steps: [
      { text: "Open **Broadcast Analytics** from the All Tools menu" },
      { text: "View the overall delivery and read rate across all broadcasts" },
      { text: "Click on a specific broadcast row to see per-message stats" },
      { text: "Use the date range filter to narrow the time window" },
    ],
    screenshot: {
      path: "/analytics",
      file: "wa-broadcast-analytics.png",
      alt: "Broadcast analytics dashboard with delivery stats",
    },
  },

  // ── Templates ──────────────────────────────────────────
  {
    slug: "templates",
    title: "How to create message templates",
    summary: "Create and submit WhatsApp message templates for Meta approval before using them in broadcasts.",
    section: "whatsapp",
    category: "Templates",
    keywords: ["template", "create", "message", "meta", "approval", "whatsapp"],
    steps: [
      { text: "Open **Templates** from the All Tools menu in the sidebar" },
      { text: "Click **+ New Template** to start creating a template" },
      { text: "Choose a category (Marketing, Utility, or Authentication)" },
      { text: "Write the header, body text (with variables like {{1}}), and footer" },
      { text: "Add buttons if needed (Quick Reply, Call to Action, or URL)" },
      { text: "Click **Submit** — Meta reviews the template (usually within minutes)" },
      { text: "Once approved, the template is available for broadcasts" },
    ],
    screenshot: {
      path: "/templates",
      file: "wa-templates.png",
      alt: "Templates page showing approved and pending templates",
    },
  },

  // ── Reminders ──────────────────────────────────────────
  {
    slug: "reminders",
    title: "How to set a reminder",
    summary: "Schedule follow-up reminders for contacts so you never miss a callback or task.",
    section: "whatsapp",
    category: "Reminders",
    keywords: ["reminder", "follow-up", "schedule", "task", "notification"],
    steps: [
      { text: "Click **Reminders** in the sidebar", target: "wa-sidebar-reminders" },
      { text: "Click **+ New Reminder** at the top-right" },
      { text: "Select the contact, set a date/time, and add a note" },
      { text: "Click **Save** — you'll be notified when it's due" },
      { text: "Mark a reminder as **done** to clear it from the list" },
    ],
    screenshot: {
      path: "/reminders",
      file: "wa-reminders.png",
      alt: "Reminders page with upcoming and completed reminders",
    },
  },

  // ── Bot Leads ──────────────────────────────────────────
  {
    slug: "bot-leads",
    title: "How to manage bot leads",
    summary: "View and process leads captured automatically by the chatbot from incoming conversations.",
    section: "whatsapp",
    category: "Bot Leads",
    keywords: ["bot", "leads", "chatbot", "auto", "capture", "convert"],
    steps: [
      { text: "Click **Bot Leads** in the sidebar", target: "wa-sidebar-leads" },
      { text: "Review the list of leads captured by the chatbot" },
      { text: "Click a lead to see their submission details and conversation" },
      { text: "Use the **status filter** to see new, contacted, or converted leads" },
      { text: "Convert a lead to a contact by clicking **Add to Contacts**" },
    ],
    screenshot: {
      path: "/leads",
      file: "wa-bot-leads.png",
      alt: "Bot leads page with lead list and status filters",
    },
  },

  // ── Media ──────────────────────────────────────────────
  {
    slug: "media-library",
    title: "How to use the media library",
    summary: "Upload and manage images, videos, and documents for use in conversations and broadcasts.",
    section: "whatsapp",
    category: "Media",
    keywords: ["media", "upload", "image", "video", "document", "library", "file"],
    steps: [
      { text: "Open **Media Library** from the All Tools menu" },
      { text: "Click **Upload** to add images, videos, or documents" },
      { text: "Drag and drop files or browse from your computer" },
      { text: "Click any file to preview it or copy the URL" },
      { text: "Media uploaded here is available when sending messages or creating broadcasts" },
    ],
    screenshot: {
      path: "/media",
      file: "wa-media-library.png",
      alt: "Media library showing uploaded images and files",
    },
  },

  // ── Quotations & Invoices ──────────────────────────────
  {
    slug: "quotations",
    title: "How to create a quotation",
    summary: "Generate a professional quotation with sport selection, area, rates, and PDF export.",
    section: "whatsapp",
    category: "Quotations",
    keywords: ["quotation", "quote", "price", "rate", "pdf", "send"],
    steps: [
      { text: "Open **Quotations** from the All Tools menu" },
      { text: "Click **+ New Quotation** to start" },
      { text: "Select the sport, area dimensions, surface type, and additional items" },
      { text: "The system calculates the total based on your saved rates" },
      { text: "Click **Generate PDF** to preview and download the quotation" },
      { text: "Use **Send via WhatsApp** to share it directly with the client" },
    ],
    screenshot: {
      path: "/quotations",
      file: "wa-quotations.png",
      alt: "Quotations page with rate calculator and PDF options",
    },
  },
  {
    slug: "invoices",
    title: "How to manage invoices",
    summary: "Convert quotations to invoices, track payment status, and download invoice PDFs.",
    section: "whatsapp",
    category: "Invoices",
    keywords: ["invoice", "payment", "billing", "pdf", "convert", "track"],
    steps: [
      { text: "Open **Invoices** from the All Tools menu" },
      { text: "Click **+ New Invoice** or convert an existing quotation to an invoice" },
      { text: "Review the line items, tax, and total amount" },
      { text: "Set the payment status (Pending, Partial, Paid)" },
      { text: "Click **Download PDF** to save or print the invoice" },
    ],
    screenshot: {
      path: "/invoices",
      file: "wa-invoices.png",
      alt: "Invoices page showing payment status tracking",
    },
  },

  // ── Court Designer ─────────────────────────────────────
  {
    slug: "court-designer",
    title: "How to use the Court Designer",
    summary: "Design 2D and 3D court layouts for any sport, customize surfaces, and export images.",
    section: "whatsapp",
    category: "Court Designer",
    keywords: ["court", "designer", "layout", "sport", "surface", "2D", "3D", "image"],
    steps: [
      { text: "Open **Court Designer** from the All Tools menu" },
      { text: "Select the **sport** (football, basketball, tennis, etc.)" },
      { text: "Choose the **surface type** and customize dimensions" },
      { text: "Switch between **2D plan view** and **3D preview**" },
      { text: "Click **Export** to download the image or share via WhatsApp" },
    ],
    screenshot: {
      path: "/court-images",
      file: "wa-court-designer.png",
      alt: "Court Designer with sport selection and 2D layout view",
    },
  },

  // ── Ad Campaigns ───────────────────────────────────────
  {
    slug: "ad-campaigns",
    title: "How to view ad campaign performance",
    summary: "Monitor Meta ad campaigns, track leads, and review AI-generated performance summaries.",
    section: "whatsapp",
    category: "Ad Campaigns",
    roles: ["admin"],
    keywords: ["ad", "campaign", "meta", "facebook", "leads", "performance"],
    steps: [
      { text: "Open **Ad Campaigns** from the All Tools menu" },
      { text: "View the list of active and past campaigns with spend and lead counts" },
      { text: "Click a campaign to drill into its metrics and individual leads" },
      { text: "Open **Lead Analytics** for city-wise demand, repeat submitters, and AI insights" },
    ],
    screenshot: {
      path: "/ad-campaigns",
      file: "wa-ad-campaigns.png",
      alt: "Ad campaigns page with campaign list and lead metrics",
    },
  },

  // ── Products & Portfolio ───────────────────────────────
  {
    slug: "products",
    title: "How to manage products",
    summary: "Maintain your catalog of floorings, materials, and equipment with TDS sheets per sport.",
    section: "whatsapp",
    category: "Products",
    keywords: ["product", "catalog", "flooring", "material", "equipment", "TDS"],
    steps: [
      { text: "Open **Products** from the All Tools menu" },
      { text: "Browse existing products by sport or category" },
      { text: "Click **+ Add Product** to add a new item" },
      { text: "Fill in name, description, pricing, and upload TDS documents" },
      { text: "Products appear in quotations and court designer selections" },
    ],
    screenshot: {
      path: "/products",
      file: "wa-products.png",
      alt: "Products catalog page with sport categories",
    },
  },
  {
    slug: "portfolio",
    title: "How to use the portfolio gallery",
    summary: "Showcase past builds, generate per-sport catalogue PDFs, and share with prospective clients.",
    section: "whatsapp",
    category: "Portfolio",
    keywords: ["portfolio", "gallery", "past", "builds", "catalogue", "pdf", "share"],
    steps: [
      { text: "Open **Portfolio** from the All Tools menu" },
      { text: "Browse completed projects by sport" },
      { text: "Click **+ Add Project** to upload images and project details" },
      { text: "Use **Generate Catalogue** to create a PDF for a specific sport" },
      { text: "Share the catalogue link directly via WhatsApp" },
    ],
    screenshot: {
      path: "/portfolio",
      file: "wa-portfolio.png",
      alt: "Portfolio gallery showing past project builds",
    },
  },

  // ── Admin ──────────────────────────────────────────────
  {
    slug: "connection-status",
    title: "How to check connection status",
    summary: "Verify your Meta API connection, token health, and reconnect if the session expires.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["connection", "meta", "api", "token", "status", "reconnect"],
    steps: [
      { text: "Open **Connection** from the All Tools menu (Admin section)" },
      { text: "Check the **status indicator** — green means connected, red means expired" },
      { text: "If expired, click **Reconnect** to re-authenticate with Meta" },
      { text: "The page also shows your phone number ID and business account details" },
    ],
    screenshot: {
      path: "/connection",
      file: "wa-connection.png",
      alt: "Connection page showing Meta API status and token health",
    },
  },
  {
    slug: "users-management",
    title: "How to manage users",
    summary: "Add team members, approve new user requests, and assign admin or sales roles.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["users", "team", "member", "role", "admin", "sales", "approve"],
    steps: [
      { text: "Open **Users** from the All Tools menu (Admin section)" },
      { text: "View all team members with their roles and last-active dates" },
      { text: "Check the **Pending Approvals** tab for new sign-up requests" },
      { text: "Click **Approve** or **Reject** for each pending user" },
      { text: "Change a user's role by clicking the role badge and selecting Admin or Sales" },
    ],
    screenshot: {
      path: "/users",
      file: "wa-users.png",
      alt: "Users management page with role assignments",
    },
  },
  {
    slug: "search",
    title: "How to use global search",
    summary: "Quickly find contacts, conversations, and broadcasts across the entire platform.",
    section: "whatsapp",
    category: "Search",
    keywords: ["search", "find", "global", "lookup"],
    steps: [
      { text: "Click **Search** in the sidebar", target: "wa-sidebar-search" },
      { text: "Type a name, phone number, or keyword in the search bar" },
      { text: "Results show matching contacts, conversations, and broadcasts" },
      { text: "Click any result to jump directly to that item" },
    ],
    screenshot: {
      path: "/search",
      file: "wa-search.png",
      alt: "Global search page with search results",
    },
  },

  // ── Filter Guides ──────────────────────────────────────
  {
    slug: "filter-inbox",
    title: "How to filter inbox conversations",
    summary: "Search conversations by name or phone, and switch between Open, Closed, and All views.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["filter", "inbox", "search", "open", "closed", "status", "conversation"],
    steps: [
      { text: "Click **Inbox** in the sidebar", target: "wa-sidebar-inbox" },
      { text: "Use the **search bar** at the top to find conversations by name, phone, or message text", target: "wa-inbox-search" },
      { text: "Click the **Open** tab to see only active conversations (default)", target: "wa-inbox-status-tabs" },
      { text: "Click **Closed** to see resolved conversations" },
      { text: "Click **All** to see every conversation regardless of status" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-filter-inbox.png",
      alt: "Inbox page with search bar and Open/Closed/All status tabs",
    },
  },
  {
    slug: "filter-contacts",
    title: "How to filter WhatsApp contacts",
    summary: "Search contacts, filter by tag, and filter by custom fields like location or city.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["filter", "contacts", "search", "tag", "field", "location", "city"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Type in the **search bar** to find contacts by name or phone number", target: "wa-contacts-search" },
      { text: "Use the **Tags dropdown** (\"All tags\") to filter by a specific tag", target: "wa-contacts-tags" },
      { text: "Use the **Filter by field** dropdown to filter by a custom field (e.g., Location, City)", target: "wa-contacts-field-filter" },
      { text: "Enter a value — the table updates instantly to show matching contacts" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-filter-contacts-full.png",
      alt: "Contacts page with search, tag filter, and field filter dropdowns",
    },
  },
  {
    slug: "filter-broadcast-recipients",
    title: "How to filter broadcast recipients",
    summary: "Use field filters or pick specific contacts when creating a broadcast to target the right audience.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["filter", "broadcast", "recipients", "field", "pick", "contacts", "target"],
    steps: [
      { text: "Click **+ New Broadcast** on the Broadcasts page", target: "wa-broadcast-create" },
      { text: "Under **Contact source**, choose \"Saved Contacts\"" },
      { text: "Select **Filter by field** to add dynamic rules (e.g., Location equals \"Mumbai\")" },
      { text: "Click **+ Add filter** to combine multiple conditions (e.g., Location + Tag)" },
      { text: "Or select **Pick specific** to manually search and select individual contacts" },
      { text: "The matching contact count updates as you adjust the filters" },
    ],
    screenshot: {
      path: "/broadcasts",
      file: "wa-filter-broadcast-recipients.png",
      alt: "Broadcast composer with recipient filter builder",
    },
  },
  {
    slug: "filter-bot-leads",
    title: "How to filter bot leads",
    summary: "Filter leads by search, chatbot path, status, and assigned rep to manage them efficiently.",
    section: "whatsapp",
    category: "Bot Leads",
    keywords: ["filter", "bot", "leads", "path", "status", "assigned", "search"],
    steps: [
      { text: "Click **Bot Leads** in the sidebar", target: "wa-sidebar-leads" },
      { text: "Use the **search bar** to find leads by name, phone, or location", target: "wa-leads-search" },
      { text: "Use the **Path** dropdown to filter by chatbot path (Turnkey, Maintenance, Consultation, Product)", target: "wa-leads-path" },
      { text: "Use the **Status** dropdown to filter by stage (New, In progress, Contacted, Converted, Lost)", target: "wa-leads-status" },
      { text: "Use the **Assigned** dropdown to see leads assigned to a specific rep, or unassigned leads", target: "wa-leads-assigned" },
      { text: "Click **Clear** to reset all filters at once" },
    ],
    screenshot: {
      path: "/leads",
      file: "wa-filter-bot-leads.png",
      alt: "Bot leads page with search, path, status, and assigned filter dropdowns",
    },
  },
  {
    slug: "filter-templates-status",
    title: "How to filter templates by status",
    summary: "View templates by approval status — draft, pending, submitted, approved, or rejected.",
    section: "whatsapp",
    category: "Templates",
    keywords: ["filter", "template", "status", "draft", "approved", "rejected", "pending"],
    steps: [
      { text: "Open **Templates** from the All Tools menu" },
      { text: "Click a **status tab** to filter: All, Draft, Pending Admin, Submitted, Approved, or Rejected", target: "wa-templates-tabs" },
      { text: "Each tab shows the count of templates in that status" },
      { text: "Admin users can toggle **Show deleted** to see removed templates" },
    ],
    screenshot: {
      path: "/templates",
      file: "wa-filter-templates.png",
      alt: "Templates page with status filter tabs",
    },
  },
  {
    slug: "filter-analytics-range",
    title: "How to filter analytics by date range",
    summary: "Switch between 7-day, 30-day, 90-day, and all-time views on the broadcast analytics page.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["filter", "analytics", "date", "range", "7 days", "30 days", "90 days"],
    steps: [
      { text: "Open **Broadcast Analytics** from the All Tools menu" },
      { text: "Click the **date range buttons** at the top: 7 days, 30 days, 90 days, or All time", target: "wa-analytics-range" },
      { text: "The charts and stats update to show only the selected period" },
      { text: "Use this to compare recent performance vs. longer-term trends" },
    ],
    screenshot: {
      path: "/analytics",
      file: "wa-filter-analytics.png",
      alt: "Analytics page with date range selector buttons",
    },
  },
  {
    slug: "filter-ad-leads",
    title: "How to filter ad campaign leads",
    summary: "Filter Meta ad leads by city, sport, area, stage, and assigned rep with searchable dropdowns.",
    section: "whatsapp",
    category: "Ad Campaigns",
    roles: ["admin"],
    keywords: ["filter", "ad", "leads", "city", "sport", "area", "stage", "assigned"],
    steps: [
      { text: "Open **Ad Campaigns** from the All Tools menu" },
      { text: "Scroll to the **Lead-gen leads** table" },
      { text: "Use the **City** dropdown to filter leads from a specific city", target: "wa-ad-filters" },
      { text: "Use the **Sport** dropdown to filter by sport interest" },
      { text: "Use the **Stage** dropdown to filter by lead stage (e.g., New, Contacted)" },
      { text: "Use the **Assigned To** dropdown to see leads assigned to a specific rep" },
      { text: "Click **Clear** to reset all filters — filters are remembered during the session" },
    ],
    screenshot: {
      path: "/ad-campaigns",
      file: "wa-filter-ad-leads.png",
      alt: "Ad campaigns page with lead filter dropdowns for city, sport, area, stage",
    },
  },
];

export const WHATSAPP_RECORDING: SectionRecording = {
  slug: "whatsapp-overview",
  title: "WhatsApp Dashboard Overview",
  section: "whatsapp",
  startUrl: "/inbox",
  actions: [
    { type: "wait", duration: 2000 },
    { type: "highlight", selector: "[data-guide='wa-inbox']", label: "Inbox" },
    { type: "click", selector: "[data-guide='wa-sidebar-broadcasts']" },
    { type: "wait", duration: 1500 },
    { type: "highlight", selector: "[data-guide='wa-broadcast-create']", label: "Create broadcast" },
    { type: "click", selector: "[data-guide='wa-sidebar-contacts']" },
    { type: "wait", duration: 1500 },
    { type: "scroll", direction: "down", amount: 400 },
    { type: "wait", duration: 1000 },
    { type: "click", selector: "[data-guide='wa-sidebar-reminders']" },
    { type: "wait", duration: 1500 },
    { type: "highlight", selector: "[data-guide='wa-sidebar-leads']", label: "Bot Leads" },
  ],
};
