import type { GuideEntry, SectionRecording } from "../types";

export const WHATSAPP_ENTRIES: GuideEntry[] = [
  // ── Inbox ──────────────────────────────────────────────
  {
    slug: "inbox-basics",
    title: "How to use the Inbox",
    summary: "Read and reply to WhatsApp conversations, send media, and assign chats to team members.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["inbox", "chat", "conversation", "reply", "message", "assign"],
    steps: [
      { text: "Click **Inbox** in the sidebar", target: "wa-sidebar-inbox" },
      { text: "Select a conversation from the left panel to open it" },
      { text: "Type your reply in the message box at the bottom and hit **Send**" },
      { text: "Use the **attachment icon** to send images, videos, or documents" },
      { text: "Click the **contact name** at the top to view their profile or assign the chat" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-inbox-basics.png",
      alt: "Inbox page showing conversation list and message composer",
    },
  },
  {
    slug: "quick-replies",
    title: "How to use quick replies",
    summary: "Save and reuse message snippets in the Inbox to reply faster.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["quick reply", "snippet", "canned", "template", "inbox"],
    steps: [
      { text: "Open a conversation in the **Inbox**", target: "wa-sidebar-inbox" },
      { text: "Click the **/ (slash)** icon in the message composer" },
      { text: "Pick a saved reply from the list, or type to search" },
      { text: "Edit the message if needed, then hit **Send**" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-quick-replies.png",
      alt: "Inbox conversation with quick reply menu open",
    },
  },

  // ── Contacts ───────────────────────────────────────────
  {
    slug: "manage-contacts",
    title: "How to add and manage contacts",
    summary: "Add new WhatsApp contacts, edit details, apply tags, and export your contact list.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["contact", "add", "create", "edit", "export", "manage"],
    steps: [
      { text: "Click **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click **+ Add Contact** at the top-right to create a new contact" },
      { text: "Fill in the name, phone number, and optional tags" },
      { text: "Click a contact row to view/edit their details, conversation history, and tags" },
      { text: "Use the **Export** button to download your contact list as a CSV" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-manage-contacts.png",
      alt: "Contacts page with add button and contact list",
    },
  },
  {
    slug: "filter-contacts-tag",
    title: "How to filter contacts by tag",
    summary: "Use tags to segment your WhatsApp contacts list for targeted broadcasts.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["contacts", "filter", "tag", "segment"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click the **Tags** filter dropdown above the table" },
      { text: "Select one or more tags — the list updates instantly" },
      { text: "Use the filtered list to start a broadcast or export contacts" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-filter-contacts.png",
      alt: "Contacts page with tag filter applied",
    },
  },
  {
    slug: "tags",
    title: "How to manage tags",
    summary: "Create, edit, and color-code tags to organize your contacts into meaningful groups.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["tags", "label", "color", "organize", "group", "category"],
    steps: [
      { text: "Open **Tags** from the All Tools menu in the sidebar" },
      { text: "Click **+ New Tag** to create a new tag" },
      { text: "Enter a tag name and pick a color" },
      { text: "Click **Save** — the tag is now available when tagging contacts" },
      { text: "Click the **edit icon** on any tag to rename or change its color" },
    ],
    screenshot: {
      path: "/tags",
      file: "wa-tags.png",
      alt: "Tags management page with color-coded tags",
    },
  },

  // ── Broadcasts ─────────────────────────────────────────
  {
    slug: "send-broadcast",
    title: "How to send a broadcast",
    summary: "Create and send a WhatsApp broadcast to a filtered set of contacts using a pre-approved template.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["broadcast", "send", "template", "bulk", "message"],
    steps: [
      { text: "Click **Broadcasts** in the sidebar", target: "wa-sidebar-broadcasts" },
      { text: "Click the **New Broadcast** button at the top-right", target: "wa-broadcast-create" },
      { text: "Select a **template** from the dropdown — only approved templates appear" },
      { text: "Use the **filters** to pick which contacts receive the broadcast (tags, date, etc.)" },
      { text: "Review the preview on the right, then click **Send Broadcast**" },
    ],
    screenshot: {
      path: "/broadcasts",
      file: "wa-send-broadcast.png",
      alt: "Broadcasts page with the New Broadcast button highlighted",
    },
  },
  {
    slug: "broadcast-analytics",
    title: "How to view broadcast analytics",
    summary: "Track delivery rates, read rates, and trends for all your broadcasts.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["analytics", "broadcast", "delivery", "read", "performance", "stats"],
    steps: [
      { text: "Open **Broadcast Analytics** from the All Tools menu" },
      { text: "View the overall delivery and read rate across all broadcasts" },
      { text: "Click on a specific broadcast row to see per-message stats" },
      { text: "Use the date range filter to narrow the time window" },
    ],
    screenshot: {
      path: "/analytics",
      file: "wa-broadcast-analytics.png",
      alt: "Broadcast analytics dashboard with delivery stats",
    },
  },

  // ── Templates ──────────────────────────────────────────
  {
    slug: "templates",
    title: "How to create message templates",
    summary: "Create and submit WhatsApp message templates for Meta approval before using them in broadcasts.",
    section: "whatsapp",
    category: "Templates",
    keywords: ["template", "create", "message", "meta", "approval", "whatsapp"],
    steps: [
      { text: "Open **Templates** from the All Tools menu in the sidebar" },
      { text: "Click **+ New Template** to start creating a template" },
      { text: "Choose a category (Marketing, Utility, or Authentication)" },
      { text: "Write the header, body text (with variables like {{1}}), and footer" },
      { text: "Add buttons if needed (Quick Reply, Call to Action, or URL)" },
      { text: "Click **Submit** — Meta reviews the template (usually within minutes)" },
      { text: "Once approved, the template is available for broadcasts" },
    ],
    screenshot: {
      path: "/templates",
      file: "wa-templates.png",
      alt: "Templates page showing approved and pending templates",
    },
  },

  // ── Reminders ──────────────────────────────────────────
  {
    slug: "reminders",
    title: "How to set a reminder",
    summary: "Schedule follow-up reminders for contacts so you never miss a callback or task.",
    section: "whatsapp",
    category: "Reminders",
    keywords: ["reminder", "follow-up", "schedule", "task", "notification"],
    steps: [
      { text: "Click **Reminders** in the sidebar", target: "wa-sidebar-reminders" },
      { text: "Click **+ New Reminder** at the top-right" },
      { text: "Select the contact, set a date/time, and add a note" },
      { text: "Click **Save** — you'll be notified when it's due" },
      { text: "Mark a reminder as **done** to clear it from the list" },
    ],
    screenshot: {
      path: "/reminders",
      file: "wa-reminders.png",
      alt: "Reminders page with upcoming and completed reminders",
    },
  },

  // ── Bot Leads ──────────────────────────────────────────
  {
    slug: "bot-leads",
    title: "How to manage bot leads",
    summary: "View and process leads captured automatically by the chatbot from incoming conversations.",
    section: "whatsapp",
    category: "Bot Leads",
    keywords: ["bot", "leads", "chatbot", "auto", "capture", "convert"],
    steps: [
      { text: "Click **Bot Leads** in the sidebar", target: "wa-sidebar-leads" },
      { text: "Review the list of leads captured by the chatbot" },
      { text: "Click a lead to see their submission details and conversation" },
      { text: "Use the **status filter** to see new, contacted, or converted leads" },
      { text: "Convert a lead to a contact by clicking **Add to Contacts**" },
    ],
    screenshot: {
      path: "/leads",
      file: "wa-bot-leads.png",
      alt: "Bot leads page with lead list and status filters",
    },
  },

  // ── Media ──────────────────────────────────────────────
  {
    slug: "media-library",
    title: "How to use the media library",
    summary: "Upload and manage images, videos, and documents for use in conversations and broadcasts.",
    section: "whatsapp",
    category: "Media",
    keywords: ["media", "upload", "image", "video", "document", "library", "file"],
    steps: [
      { text: "Open **Media Library** from the All Tools menu" },
      { text: "Click **Upload** to add images, videos, or documents" },
      { text: "Drag and drop files or browse from your computer" },
      { text: "Click any file to preview it or copy the URL" },
      { text: "Media uploaded here is available when sending messages or creating broadcasts" },
    ],
    screenshot: {
      path: "/media",
      file: "wa-media-library.png",
      alt: "Media library showing uploaded images and files",
    },
  },

  // ── Quotations & Invoices ──────────────────────────────
  {
    slug: "quotations",
    title: "How to create a quotation",
    summary: "Generate a professional quotation with sport selection, area, rates, and PDF export.",
    section: "whatsapp",
    category: "Quotations",
    keywords: ["quotation", "quote", "price", "rate", "pdf", "send"],
    steps: [
      { text: "Open **Quotations** from the All Tools menu" },
      { text: "Click **+ New Quotation** to start" },
      { text: "Select the sport, area dimensions, surface type, and additional items" },
      { text: "The system calculates the total based on your saved rates" },
      { text: "Click **Generate PDF** to preview and download the quotation" },
      { text: "Use **Send via WhatsApp** to share it directly with the client" },
    ],
    screenshot: {
      path: "/quotations",
      file: "wa-quotations.png",
      alt: "Quotations page with rate calculator and PDF options",
    },
  },
  {
    slug: "invoices",
    title: "How to manage invoices",
    summary: "Convert quotations to invoices, track payment status, and download invoice PDFs.",
    section: "whatsapp",
    category: "Invoices",
    keywords: ["invoice", "payment", "billing", "pdf", "convert", "track"],
    steps: [
      { text: "Open **Invoices** from the All Tools menu" },
      { text: "Click **+ New Invoice** or convert an existing quotation to an invoice" },
      { text: "Review the line items, tax, and total amount" },
      { text: "Set the payment status (Pending, Partial, Paid)" },
      { text: "Click **Download PDF** to save or print the invoice" },
    ],
    screenshot: {
      path: "/invoices",
      file: "wa-invoices.png",
      alt: "Invoices page showing payment status tracking",
    },
  },

  // ── Court Designer ─────────────────────────────────────
  {
    slug: "court-designer",
    title: "How to use the Court Designer",
    summary: "Design 2D and 3D court layouts for any sport, customize surfaces, and export images.",
    section: "whatsapp",
    category: "Court Designer",
    keywords: ["court", "designer", "layout", "sport", "surface", "2D", "3D", "image"],
    steps: [
      { text: "Open **Court Designer** from the All Tools menu" },
      { text: "Select the **sport** (football, basketball, tennis, etc.)" },
      { text: "Choose the **surface type** and customize dimensions" },
      { text: "Switch between **2D plan view** and **3D preview**" },
      { text: "Click **Export** to download the image or share via WhatsApp" },
    ],
    screenshot: {
      path: "/court-images",
      file: "wa-court-designer.png",
      alt: "Court Designer with sport selection and 2D layout view",
    },
  },

  // ── Ad Campaigns ───────────────────────────────────────
  {
    slug: "ad-campaigns",
    title: "How to view ad campaign performance",
    summary: "Monitor Meta ad campaigns, track leads, and review AI-generated performance summaries.",
    section: "whatsapp",
    category: "Ad Campaigns",
    roles: ["admin"],
    keywords: ["ad", "campaign", "meta", "facebook", "leads", "performance"],
    steps: [
      { text: "Open **Ad Campaigns** from the All Tools menu" },
      { text: "View the list of active and past campaigns with spend and lead counts" },
      { text: "Click a campaign to drill into its metrics and individual leads" },
      { text: "Open **Lead Analytics** for city-wise demand, repeat submitters, and AI insights" },
    ],
    screenshot: {
      path: "/ad-campaigns",
      file: "wa-ad-campaigns.png",
      alt: "Ad campaigns page with campaign list and lead metrics",
    },
  },

  // ── Products & Portfolio ───────────────────────────────
  {
    slug: "products",
    title: "How to manage products",
    summary: "Maintain your catalog of floorings, materials, and equipment with TDS sheets per sport.",
    section: "whatsapp",
    category: "Products",
    keywords: ["product", "catalog", "flooring", "material", "equipment", "TDS"],
    steps: [
      { text: "Open **Products** from the All Tools menu" },
      { text: "Browse existing products by sport or category" },
      { text: "Click **+ Add Product** to add a new item" },
      { text: "Fill in name, description, pricing, and upload TDS documents" },
      { text: "Products appear in quotations and court designer selections" },
    ],
    screenshot: {
      path: "/products",
      file: "wa-products.png",
      alt: "Products catalog page with sport categories",
    },
  },
  {
    slug: "portfolio",
    title: "How to use the portfolio gallery",
    summary: "Showcase past builds, generate per-sport catalogue PDFs, and share with prospective clients.",
    section: "whatsapp",
    category: "Portfolio",
    keywords: ["portfolio", "gallery", "past", "builds", "catalogue", "pdf", "share"],
    steps: [
      { text: "Open **Portfolio** from the All Tools menu" },
      { text: "Browse completed projects by sport" },
      { text: "Click **+ Add Project** to upload images and project details" },
      { text: "Use **Generate Catalogue** to create a PDF for a specific sport" },
      { text: "Share the catalogue link directly via WhatsApp" },
    ],
    screenshot: {
      path: "/portfolio",
      file: "wa-portfolio.png",
      alt: "Portfolio gallery showing past project builds",
    },
  },

  // ── Admin ──────────────────────────────────────────────
  {
    slug: "connection-status",
    title: "How to check connection status",
    summary: "Verify your Meta API connection, token health, and reconnect if the session expires.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["connection", "meta", "api", "token", "status", "reconnect"],
    steps: [
      { text: "Open **Connection** from the All Tools menu (Admin section)" },
      { text: "Check the **status indicator** — green means connected, red means expired" },
      { text: "If expired, click **Reconnect** to re-authenticate with Meta" },
      { text: "The page also shows your phone number ID and business account details" },
    ],
    screenshot: {
      path: "/connection",
      file: "wa-connection.png",
      alt: "Connection page showing Meta API status and token health",
    },
  },
  {
    slug: "users-management",
    title: "How to manage users",
    summary: "Add team members, approve new user requests, and assign admin or sales roles.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["users", "team", "member", "role", "admin", "sales", "approve"],
    steps: [
      { text: "Open **Users** from the All Tools menu (Admin section)" },
      { text: "View all team members with their roles and last-active dates" },
      { text: "Check the **Pending Approvals** tab for new sign-up requests" },
      { text: "Click **Approve** or **Reject** for each pending user" },
      { text: "Change a user's role by clicking the role badge and selecting Admin or Sales" },
    ],
    screenshot: {
      path: "/users",
      file: "wa-users.png",
      alt: "Users management page with role assignments",
    },
  },
  {
    slug: "search",
    title: "How to use global search",
    summary: "Quickly find contacts, conversations, and broadcasts across the entire platform.",
    section: "whatsapp",
    category: "Search",
    keywords: ["search", "find", "global", "lookup"],
    steps: [
      { text: "Click **Search** in the sidebar", target: "wa-sidebar-search" },
      { text: "Type a name, phone number, or keyword in the search bar" },
      { text: "Results show matching contacts, conversations, and broadcasts" },
      { text: "Click any result to jump directly to that item" },
    ],
    screenshot: {
      path: "/search",
      file: "wa-search.png",
      alt: "Global search page with search results",
    },
  },

  // ── Filter Guides ──────────────────────────────────────
  {
    slug: "filter-inbox",
    title: "How to filter inbox conversations",
    summary: "Search conversations by name or phone, and switch between Open, Closed, and All views.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["filter", "inbox", "search", "open", "closed", "status", "conversation"],
    steps: [
      { text: "Click **Inbox** in the sidebar", target: "wa-sidebar-inbox" },
      { text: "Use the **search bar** at the top to find conversations by name, phone, or message text", target: "wa-inbox-search" },
      { text: "Click the **Open** tab to see only active conversations (default)", target: "wa-inbox-status-tabs" },
      { text: "Click **Closed** to see resolved conversations" },
      { text: "Click **All** to see every conversation regardless of status" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-filter-inbox.png",
      alt: "Inbox page with search bar and Open/Closed/All status tabs",
    },
  },
  {
    slug: "filter-contacts",
    title: "How to filter WhatsApp contacts",
    summary: "Search contacts, filter by tag, and filter by custom fields like location or city.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["filter", "contacts", "search", "tag", "field", "location", "city"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Type in the **search bar** to find contacts by name or phone number", target: "wa-contacts-search" },
      { text: "Use the **Tags dropdown** (\"All tags\") to filter by a specific tag", target: "wa-contacts-tags" },
      { text: "Use the **Filter by field** dropdown to filter by a custom field (e.g., Location, City)", target: "wa-contacts-field-filter" },
      { text: "Enter a value — the table updates instantly to show matching contacts" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-filter-contacts-full.png",
      alt: "Contacts page with search, tag filter, and field filter dropdowns",
    },
  },
  {
    slug: "filter-broadcast-recipients",
    title: "How to filter broadcast recipients",
    summary: "Use field filters or pick specific contacts when creating a broadcast to target the right audience.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["filter", "broadcast", "recipients", "field", "pick", "contacts", "target"],
    steps: [
      { text: "Click **+ New Broadcast** on the Broadcasts page", target: "wa-broadcast-create" },
      { text: "Under **Contact source**, choose \"Saved Contacts\"" },
      { text: "Select **Filter by field** to add dynamic rules (e.g., Location equals \"Mumbai\")" },
      { text: "Click **+ Add filter** to combine multiple conditions (e.g., Location + Tag)" },
      { text: "Or select **Pick specific** to manually search and select individual contacts" },
      { text: "The matching contact count updates as you adjust the filters" },
    ],
    screenshot: {
      path: "/broadcasts",
      file: "wa-filter-broadcast-recipients.png",
      alt: "Broadcast composer with recipient filter builder",
    },
  },
  {
    slug: "filter-bot-leads",
    title: "How to filter bot leads",
    summary: "Filter leads by search, chatbot path, status, and assigned rep to manage them efficiently.",
    section: "whatsapp",
    category: "Bot Leads",
    keywords: ["filter", "bot", "leads", "path", "status", "assigned", "search"],
    steps: [
      { text: "Click **Bot Leads** in the sidebar", target: "wa-sidebar-leads" },
      { text: "Use the **search bar** to find leads by name, phone, or location", target: "wa-leads-search" },
      { text: "Use the **Path** dropdown to filter by chatbot path (Turnkey, Maintenance, Consultation, Product)", target: "wa-leads-path" },
      { text: "Use the **Status** dropdown to filter by stage (New, In progress, Contacted, Converted, Lost)", target: "wa-leads-status" },
      { text: "Use the **Assigned** dropdown to see leads assigned to a specific rep, or unassigned leads", target: "wa-leads-assigned" },
      { text: "Click **Clear** to reset all filters at once" },
    ],
    screenshot: {
      path: "/leads",
      file: "wa-filter-bot-leads.png",
      alt: "Bot leads page with search, path, status, and assigned filter dropdowns",
    },
  },
  {
    slug: "filter-templates-status",
    title: "How to filter templates by status",
    summary: "View templates by approval status — draft, pending, submitted, approved, or rejected.",
    section: "whatsapp",
    category: "Templates",
    keywords: ["filter", "template", "status", "draft", "approved", "rejected", "pending"],
    steps: [
      { text: "Open **Templates** from the All Tools menu" },
      { text: "Click a **status tab** to filter: All, Draft, Pending Admin, Submitted, Approved, or Rejected", target: "wa-templates-tabs" },
      { text: "Each tab shows the count of templates in that status" },
      { text: "Admin users can toggle **Show deleted** to see removed templates" },
    ],
    screenshot: {
      path: "/templates",
      file: "wa-filter-templates.png",
      alt: "Templates page with status filter tabs",
    },
  },
  {
    slug: "filter-analytics-range",
    title: "How to filter analytics by date range",
    summary: "Switch between 7-day, 30-day, 90-day, and all-time views on the broadcast analytics page.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["filter", "analytics", "date", "range", "7 days", "30 days", "90 days"],
    steps: [
      { text: "Open **Broadcast Analytics** from the All Tools menu" },
      { text: "Click the **date range buttons** at the top: 7 days, 30 days, 90 days, or All time", target: "wa-analytics-range" },
      { text: "The charts and stats update to show only the selected period" },
      { text: "Use this to compare recent performance vs. longer-term trends" },
    ],
    screenshot: {
      path: "/analytics",
      file: "wa-filter-analytics.png",
      alt: "Analytics page with date range selector buttons",
    },
  },
  {
    slug: "filter-ad-leads",
    title: "How to filter ad campaign leads",
    summary: "Filter Meta ad leads by city, sport, area, stage, and assigned rep with searchable dropdowns.",
    section: "whatsapp",
    category: "Ad Campaigns",
    roles: ["admin"],
    keywords: ["filter", "ad", "leads", "city", "sport", "area", "stage", "assigned"],
    steps: [
      { text: "Open **Ad Campaigns** from the All Tools menu" },
      { text: "Scroll to the **Lead-gen leads** table" },
      { text: "Use the **City** dropdown to filter leads from a specific city", target: "wa-ad-filters" },
      { text: "Use the **Sport** dropdown to filter by sport interest" },
      { text: "Use the **Stage** dropdown to filter by lead stage (e.g., New, Contacted)" },
      { text: "Use the **Assigned To** dropdown to see leads assigned to a specific rep" },
      { text: "Click **Clear** to reset all filters — filters are remembered during the session" },
    ],
    screenshot: {
      path: "/ad-campaigns",
      file: "wa-filter-ad-leads.png",
      alt: "Ad campaigns page with lead filter dropdowns for city, sport, area, stage",
    },
  },

  // ── Additional Inbox Guides ───────────────────────────
  {
    slug: "close-conversation",
    title: "How to close and reopen a conversation",
    summary: "Mark conversations as closed when resolved, and reopen them if the customer writes back.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["close", "reopen", "resolve", "conversation", "inbox", "archive"],
    steps: [
      { text: "Open a conversation in the **Inbox**", target: "wa-sidebar-inbox" },
      { text: "Click the **Close** button (or checkmark icon) at the top of the chat" },
      { text: "The conversation moves to the **Closed** tab" },
      { text: "To reopen, switch to the **Closed** tab and click the conversation" },
      { text: "Send a new message or click **Reopen** to move it back to Open" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-close-conversation.png",
      alt: "Inbox conversation with close button highlighted",
    },
  },
  {
    slug: "create-quick-replies",
    title: "How to create and manage quick replies",
    summary: "Save message snippets as quick replies so your team can respond faster in the Inbox.",
    section: "whatsapp",
    category: "Inbox",
    keywords: ["quick reply", "create", "snippet", "manage", "canned", "save"],
    steps: [
      { text: "Open a conversation in the **Inbox**", target: "wa-sidebar-inbox" },
      { text: "Click the **/ (slash)** icon in the message composer" },
      { text: "Click **Manage quick replies** at the bottom of the list" },
      { text: "Click **+ New** to create a new quick reply" },
      { text: "Enter a **shortcut** (e.g., \"greeting\") and the **message text**" },
      { text: "Click **Save** — the quick reply is now available for all team members" },
    ],
    screenshot: {
      path: "/inbox",
      file: "wa-create-quick-replies.png",
      alt: "Quick replies management panel with create form",
    },
  },

  // ── Additional Contacts Guides ────────────────────────
  {
    slug: "contact-detail",
    title: "How to view contact details",
    summary: "Open a contact's full profile to see their info, tags, conversation history, and deals.",
    section: "whatsapp",
    category: "Contacts",
    keywords: ["contact", "detail", "profile", "view", "info", "history"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click on a contact's name in the table to open their detail page" },
      { text: "View their phone number, tags, custom fields, and notes" },
      { text: "Scroll down to see their conversation history and any linked deals" },
      { text: "Click **Edit** to update their information or **Add Tag** to apply new tags" },
    ],
    screenshot: {
      path: "/contacts",
      file: "wa-contact-detail.png",
      alt: "Contact detail page showing profile info and history",
    },
  },
  {
    slug: "duplicate-contacts",
    title: "How to merge duplicate contacts",
    summary: "Find and merge contacts that share the same phone number to keep your list clean.",
    section: "whatsapp",
    category: "Contacts",
    roles: ["admin"],
    keywords: ["duplicate", "merge", "clean", "phone", "deduplicate"],
    steps: [
      { text: "Go to **Contacts** in the sidebar", target: "wa-sidebar-contacts" },
      { text: "Click the **Duplicates** link to open the duplicates page" },
      { text: "Review groups of contacts that share the same phone number" },
      { text: "Select which contact should be the **primary** (tags from all will be unified)" },
      { text: "Click **Merge** to combine the duplicates into one contact", target: "wa-duplicates-merge" },
    ],
    screenshot: {
      path: "/contacts/duplicates",
      file: "wa-duplicate-contacts.png",
      alt: "Duplicates page with grouped contacts and merge buttons",
    },
  },

  // ── Additional Broadcast Guides ───────────────────────
  {
    slug: "broadcast-results",
    title: "How to view broadcast results",
    summary: "Check delivery status, read rates, and per-contact results for a sent broadcast.",
    section: "whatsapp",
    category: "Broadcasts",
    keywords: ["broadcast", "results", "detail", "delivery", "status", "read", "sent"],
    steps: [
      { text: "Click **Broadcasts** in the sidebar", target: "wa-sidebar-broadcasts" },
      { text: "Click on a completed broadcast row to open its detail page" },
      { text: "View the summary: total sent, delivered, read, and failed counts" },
      { text: "Scroll down to see **per-contact status** (delivered, read, or failed)" },
      { text: "Use this data to identify contacts with invalid numbers or delivery issues" },
    ],
    screenshot: {
      path: "/broadcasts",
      file: "wa-broadcast-results.png",
      alt: "Broadcast detail page with delivery stats and per-contact status",
    },
  },

  // ── Additional Quotation Guides ───────────────────────
  {
    slug: "share-quotation",
    title: "How to share a quotation via WhatsApp",
    summary: "Generate a quotation PDF and send it directly to the client through WhatsApp.",
    section: "whatsapp",
    category: "Quotations",
    keywords: ["share", "quotation", "whatsapp", "send", "pdf", "client"],
    steps: [
      { text: "Open **Quotations** from the All Tools menu" },
      { text: "Create a new quotation or open an existing one" },
      { text: "Click **Generate PDF** to create the quotation document" },
      { text: "Click **Send via WhatsApp** to share the PDF with the client" },
      { text: "Select the contact from the list or enter a phone number" },
      { text: "The quotation is sent as a document message in the chat" },
    ],
    screenshot: {
      path: "/quotations",
      file: "wa-share-quotation.png",
      alt: "Quotation page with Send via WhatsApp button",
    },
  },

  // ── Additional Portfolio Guides ───────────────────────
  {
    slug: "share-portfolio",
    title: "How to share portfolio and court designs",
    summary: "Share your portfolio catalogue or court design via a public link or WhatsApp message.",
    section: "whatsapp",
    category: "Portfolio",
    keywords: ["share", "portfolio", "court", "design", "link", "public", "catalogue"],
    steps: [
      { text: "Open **Portfolio** from the All Tools menu to share a project catalogue" },
      { text: "Click **Generate Catalogue** for a sport to create a shareable PDF" },
      { text: "Use the **Share** button to copy the public link or send via WhatsApp" },
      { text: "For court designs, open **Court Designer** and create or select a layout" },
      { text: "Click **Export** and choose **Share link** to get a public URL" },
      { text: "Share the link directly with clients — they can view it without logging in" },
    ],
    screenshot: {
      path: "/portfolio",
      file: "wa-share-portfolio.png",
      alt: "Portfolio page with share and catalogue options",
    },
  },

  // ── Additional Ad Campaign Guides ─────────────────────
  {
    slug: "lead-analytics",
    title: "How to view lead analytics",
    summary: "Analyze ad leads by city, sport demand, repeat submitters, and AI-generated insights.",
    section: "whatsapp",
    category: "Ad Campaigns",
    roles: ["admin"],
    keywords: ["lead", "analytics", "city", "sport", "demand", "repeat", "AI", "insight"],
    steps: [
      { text: "Open **Lead Analytics** from the Meta Ads section in All Tools" },
      { text: "View the city-wise demand breakdown showing which cities generate the most leads", target: "wa-lead-city" },
      { text: "Check the **Sport demand** chart to see which sports are most popular", target: "wa-lead-sport" },
      { text: "Review **Repeat submitters** to identify leads who have submitted multiple times" },
      { text: "Read the **AI insights** section for automated performance summaries", target: "wa-lead-ai" },
    ],
    screenshot: {
      path: "/ad-campaigns/lead-analytics",
      file: "wa-lead-analytics.png",
      alt: "Lead analytics page with city demand and AI insights",
    },
  },

  // ── Additional Admin Guides ───────────────────────────
  {
    slug: "quotation-rates",
    title: "How to configure quotation rates",
    summary: "Set default pricing rates per sport and surface type used in quotation calculations.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["rates", "pricing", "quotation", "sport", "surface", "configure", "settings"],
    steps: [
      { text: "Open **Quotation rates** from the Organization section in All Tools" },
      { text: "Select a sport to configure its rate sheet", target: "wa-rates-sport" },
      { text: "Set the per-square-foot or per-square-meter rate for each surface type" },
      { text: "Add pricing for additional items (fencing, lighting, markings, etc.)" },
      { text: "Click **Save** — new quotations will use these updated rates", target: "wa-rates-save" },
    ],
    screenshot: {
      path: "/settings/quotation-rates",
      file: "wa-quotation-rates.png",
      alt: "Quotation rates page with sport pricing configuration",
    },
  },
  {
    slug: "chatbot-test",
    title: "How to test the chatbot",
    summary: "Simulate conversations with the chatbot to verify flow paths and responses.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["chatbot", "test", "simulate", "flow", "bot", "conversation"],
    steps: [
      { text: "Navigate to the **Chatbot Test** page from the Admin section" },
      { text: "Type a message in the chat simulator as if you were a customer", target: "wa-chatbot-input" },
      { text: "The chatbot responds following its configured flow paths" },
      { text: "Test different paths (Turnkey, Maintenance, Consultation, Product)", target: "wa-chatbot-path" },
      { text: "Verify that the bot collects the correct information at each step" },
    ],
    screenshot: {
      path: "/admin/chatbot-test",
      file: "wa-chatbot-test.png",
      alt: "Chatbot test page with conversation simulator",
    },
  },
  {
    slug: "sport-tds",
    title: "How to manage sport TDS sheets",
    summary: "Upload and organize Technical Data Sheets for each sport's flooring and surface products.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["TDS", "technical", "data", "sheet", "sport", "flooring", "upload"],
    steps: [
      { text: "Navigate to the **Sport TDS** page from the Admin section" },
      { text: "Select a sport to view its linked TDS documents" },
      { text: "Click **Upload TDS** to add a new Technical Data Sheet", target: "wa-tds-upload" },
      { text: "Each TDS is linked to its product and appears in quotation PDFs" },
      { text: "Click **Delete** to remove an outdated TDS document" },
    ],
    screenshot: {
      path: "/admin/sport-tds",
      file: "wa-sport-tds.png",
      alt: "Sport TDS management page with document list",
    },
  },
  {
    slug: "audit-log",
    title: "How to view the audit log",
    summary: "Review a chronological record of all stage changes, role changes, and taxonomy edits.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["audit", "log", "history", "changes", "track", "record"],
    steps: [
      { text: "Open **Audit log** from the Admin section in All Tools" },
      { text: "View a chronological list of all changes made in the platform", target: "wa-audit-list" },
      { text: "Each entry shows who made the change, what changed, and when" },
      { text: "Filter by date range to narrow down to a specific period" },
      { text: "Use the audit log to track stage changes, role updates, and taxonomy edits" },
    ],
    screenshot: {
      path: "/admin/audit-log",
      file: "wa-audit-log.png",
      alt: "Audit log showing change history entries",
    },
  },
  {
    slug: "ai-usage",
    title: "How to track AI usage",
    summary: "Monitor who is using AI features, request counts, and estimated spend.",
    section: "whatsapp",
    category: "Admin",
    roles: ["admin"],
    keywords: ["AI", "usage", "cost", "requests", "spend", "monitor"],
    steps: [
      { text: "Open **AI usage** from the Admin section in All Tools" },
      { text: "View the total AI requests and estimated spend for the current period", target: "wa-ai-chart" },
      { text: "See a breakdown by team member to identify who uses AI the most", target: "wa-ai-breakdown" },
      { text: "Monitor usage trends over time to manage costs" },
      { text: "Use this data to set usage guidelines for your team" },
    ],
    screenshot: {
      path: "/admin/ai-usage",
      file: "wa-ai-usage.png",
      alt: "AI usage page with request counts and spend breakdown",
    },
  },
];

export const WHATSAPP_RECORDING: SectionRecording = {
  slug: "whatsapp-overview",
  title: "WhatsApp Dashboard Overview",
  section: "whatsapp",
  startUrl: "/inbox",
  actions: [
    { type: "wait", duration: 2000 },
    { type: "highlight", selector: "[data-guide='wa-inbox']", label: "Inbox" },
    { type: "click", selector: "[data-guide='wa-sidebar-broadcasts']" },
    { type: "wait", duration: 1500 },
    { type: "highlight", selector: "[data-guide='wa-broadcast-create']", label: "Create broadcast" },
    { type: "click", selector: "[data-guide='wa-sidebar-contacts']" },
    { type: "wait", duration: 1500 },
    { type: "scroll", direction: "down", amount: 400 },
    { type: "wait", duration: 1000 },
    { type: "click", selector: "[data-guide='wa-sidebar-reminders']" },
    { type: "wait", duration: 1500 },
    { type: "highlight", selector: "[data-guide='wa-sidebar-leads']", label: "Bot Leads" },
  ],
};
